- name: install packages
  apt:
    pkg: "{{ item }}"
  with_items:
    - nginx
    - fcgiwrap

- name: configure api endpoint
  template:
    src: templates/default.conf
    dest: /etc/nginx/sites-available/default
  notify:
    - reload nginx

- name: add limit_req_zone
  copy:
    src: files/rate_limit.conf
    dest: /etc/nginx/conf.d
  notify:
    - reload nginx

- name: install html page
  template:
    src: "templates/{{ item }}"
    dest: "{{ overpass_webroot_dir }}"
  with_items:
    - index.html
    - api.html
  notify:
    - reload nginx
