---
- name: restart munin-node
  service:
    name: munin-node
    state: restarted

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: restart fcgiwrap
  service:
    name: fcgiwrap
    state: restarted
