- name: check if apache installed
  command: /usr/bin/test -e /etc/apache2/conf-available/ -a -e /etc/apache2/conf-enabled/
  ignore_errors: True
  register: common_apache_installed

- name: install packages for apache2
  apt:
    pkg: "{{ item }}"
  with_items:
    - libwww-perl    # for munin
    - lynx           # for apache2ctl
  when: common_apache_installed.rc == 0

- name: add apache munin plugin links
  file:
    state: link
    src: "{{ item.src }}"
    dest: "/etc/munin/plugins/{{ item.dest }}"
    force: no
  notify:
    - restart munin-node
  with_items:
    - {src: /usr/share/munin/plugins/apache_accesses, dest: apache_accesses}
    - {src: /usr/share/munin/plugins/apache_processes, dest: apache_processes}
    - {src: /usr/share/munin/plugins/apache_volume, dest: apache_volume}
  when: common_apache_installed.rc == 0

# change logformat from %h to %a to support reverse proxy
- name: configure logformat for apache
  copy:
    src: "apache-logformat.conf"
    dest: "/etc/apache2/conf-available/ansible-logformat.conf"
    owner: root
    group: root
    mode: 0644
  notify: reload apache
  when: common_apache_installed.rc == 0

- name: enable logformat config for apache
  file:
    src:  /etc/apache2/conf-available/ansible-logformat.conf
    dest: /etc/apache2/conf-enabled/ansible-logformat.conf
    state: link
  notify: reload apache
  when: common_apache_installed.rc == 0

# enable mod_remoteip for reverse proxy
- name: configure remoteip
  template:
    src: apache-remoteip.conf
    dest: /etc/apache2/mods-available/remoteip.conf
    mode: 0644
    owner: root
    group: root
  notify: reload apache
  when: common_apache_installed.rc == 0 and vm_host is defined

- name: enable mod_remoteip
  file:
    src:  "/etc/apache2/mods-available/{{ item }}"
    dest: "/etc/apache2/mods-enabled/{{ item }}"
    state: link
  notify: restart apache
  with_items:
    - remoteip.load
    - remoteip.conf
  when: common_apache_installed.rc == 0 and vm_host is defined
