- name: init https keys directory
  file: path=/etc/apache2/ssl/ state=directory owner=root group=root mode=0600 force=no
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install https keys
  copy: src="ssl/{{ item }}" dest="//etc/apache2/ssl/{{ item }}" owner=root group=root mode=0600
  notify: restart apache
  with_items:
    - wildcard.cert.pem
    - wildcard.chain.pem
    - wildcard.key.pem
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: check name of default-ssl
  command: /usr/bin/test -e /etc/apache2/sites-available/default-ssl.conf
  ignore_errors: True
  register: apache_default_ssl_conf
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: set apache_default_ssl to default-ssl.conf
  set_fact: apache_default_ssl=default-ssl.conf
  when: apache_default_ssl_conf.rc == 0 and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- name: set apache_default_ssl to default-ssl
  set_fact: apache_default_ssl=default-ssl
  when: apache_default_ssl_conf.rc != 0 and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')


- name: add apache ssl module
  command: a2enmod ssl
  notify: restart apache
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: configure https keys
  lineinfile: dest="/etc/apache2/sites-available/{{ apache_default_ssl }}" regexp="{{ item.regexp }}" line="{{ item.line }}" insertbefore="{{ item.before }}"
  notify: restart apache
  with_items:
    - {regexp: "^[ 	]*SSLCertificateFile.*",
       before: "^[ 	]*SSLCertificateFile",
       line:   "	SSLCertificateFile	/etc/apache2/ssl/wildcard.cert.pem"}
    - {regexp: "^[ 	]*SSLCertificateKeyFile.*",
       before: "^[ 	]*SSLCertificateFile",
       line:   "	SSLCertificateKeyFile	/etc/apache2/ssl/wildcard.key.pem"}
    - {regexp: "^[ 	]*SSLCertificateChainFile.*",
       before: "^[ 	]*SSLCertificateFile",
       line:   "	SSLCertificateChainFile	/etc/apache2/ssl/wildcard.chain.pem"}
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: enable virtualhost on https
  lineinfile: dest=/etc/apache2/ports.conf regexp="^ *NameVirtualHost \*:443" line="    NameVirtualHost *:443" insertafter="<IfModule mod_ssl.c>"
  notify: restart apache
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: add apache ssl site
  file: src="/etc/apache2/sites-available/{{ item.a }}" dest="/etc/apache2/sites-enabled/{{ item.b }}" state=link
  notify: restart apache
  with_items:
    - {a: "{{ apache_default_ssl }}", b: "000-{{ apache_default_ssl }}" }
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: delete default-ssl link
  file: dest="/etc/apache2/sites-enabled/{{ apache_default_ssl }}" state=absent
  notify: restart apache
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: check apache configuration
  command: apache2ctl configtest
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
